.TH "datasniffer" "1" "1.0.3 DEC 17 2008" "drm_tools" "User Commands"
.SH NAME

datasniffer \- dump data from a binary file

.SH SYNOPSIS

.B datasniffer [options...]

.SH DESCRIPTION

.B datasniffer
is intended for use in reverse engineering binary data files whose contents
are known (more or less) but whose internal organization is not known.
.B datasniffer
reads data from a specified input one byte at a time and dumps the indicated data types to
a specified output after formatting each data type
as requested.  Each input byte results in an output line containing
all of the requested formats of all of the requested data types.
By examining this output a user may find the expected values and from that
may be able to determine the file's internal structure.

.B datasniffer
is part of the
.B drm_tools
package which may be obtained from:
.B http://sourceforge.net/projects/drmtools/


.SH OPTIONS

.TP
.BI -in " <input_file>"
Read input from the specified file.  Use
.B -
to read from stdin.  Default is to read from stdin.

.TP
.BI -out " <output_file>"
Write output to the specified file.  Use
.B -
to write to stdout.  Default is to write to stdout.

.TP
.BI -o " <offset>"
Emit data starting at 
.B " <offset>"
bytes from the
beginning of the file.  Default is 0.

.TP
.BI -l " <multiple>"
The number of bytes to dump.  Default is 0 = all.

.TP
.BI -c " <columns>"
Emit formatted data for
.B " <columns>"
bytes for each output line.  The first "column"
in a line will show all combinations of data types, formats, and byte orders
for the data starting on that byte.
The second column will do the same for the next byte, and so forth.
Consequently the resulting data dump
is most legible when only a single data type, format and byte order
are displayed. 
Default is 1.  


.TP
.BI -n  " <number>"
Specify line numbering options by including one or more of the
characters from the list below.  Default is 
.B a0xd.
Note that when any specification of number options must include
at least one of
.BR "x" ", " "d" ", or " "o" "."
.nf
.BR "n" " no numbering"
.BR "a" " absolute position  (number from start of file)"
.BR "r" " relative  position (number from offset)"
.BR "0" " number from 0"
.BR "1" " number from 1"
.BR "x" " print position in hexadecimal"
.BR "d" " print position in decimal"
.BR "o" " print position in octal"
.fi

.TP
.BI -d " <data_type>"
Specify the types of data to display by including characters from the list below. 
Default is
.B CSL.
.nf
.BR "c" " signed char"
.BR "s" " signed short int"
.BR "l" " signed (long) int"
.BR "g" " signed long long (not available on all platforms)"
.BR "f" " signed float"
.BR "d" " signed double"
.BR "C" " unsigned char"
.BR "S" " unsigned short int"
.BR "L" " unsigned (long) int"
.BR "G" " unsigned long long (not available on all platforms)"
.fi

.TP
.BI -b " <byte_order>"
Specify the order of bytes in the data by including characters from the list below. 
Default is
.B f.
.nf
.BR "f" " forward (as read from data)"
.BR "r" " reverse (invert order for each data size)"
.fi

.TP
.BI -r " <N>"
Header line control. The default value is
.B INT_MAX
which results in a single header line at the start of the output.
.nf
.BR "0" " no headers"
.BR "N" " one header at start of output and then every " "N" " output lines after that"
.fi

.TP
.B -p
Emit a page break before every header except the first.  If printed as text
most printers will respect the page break and start a new page before
each header line.

.TP
.B -ds
Emit data sizes and exit.

.TP
.B -h -help --help -? --??
Print the help message and exit. 

.TP
.B -i
Emit version, copyright, license and contact information and exit.





.TP
Format options which may be specified for the -f* parameters:
.B c
char,
.B d 
decimal,
.B x
hexadecimal,
.B o
octal,
.B f
float,
.B e
exp.

.TP
.BI   -fc " [cdxo]"
.BR "" "Emit the " "c" " and " "C" " data types with the formats specified. "
If the character isn't printable c format emits an "NP".  Default is 
.BR "cx" "."

.TP
.BI   -fs " [dxo]"
.BR "" "Emit the " "s" " and " "S" " data types with the formats specified. "
Default is
.BR "dx" "."

.TP
.BI   -fl " [dxo]"
.BR "" "Emit the " "l" " and " "L" " data types with the formats specified. "
Default is
.BR "dx" "."

.TP
.BI   -fg " [dxo]"
.BR "" "Emit the " "g" " and " "G" " data types with the formats specified. "
Default is 
.BR "dx" "."

.TP
.BI   -ff " [fe]"
.BR "" "Emit the " "f" " data type with the formats specified. "
Note that format
.B f
may exceed the field width, in which case the data is
shown as a "*". Use format
.B e
to see the full range of the data.  Default is 
.BR "f" "."


.TP
.BI   -fd " [fe]"
.BR "" "Emit the " "d" " data type with the formats specified. "
Note that format
.B f
may exceed the field width, in which case the data is
shown as a "*". Use format
.B e
to see the full range of the data.   Default is 
.BR "f" "."

.SH EXAMPLES

.TP
.B % datasniffer -h
List the the command line options.


.TP
.B "% echo ABCD | datasniffer -d cs -n d -fc c -fs x -b fr"
.nf
 P0AbsDec  c(+,%c)  c(-,%c)  s(+,%x)  s(-,%x) 
        0        A        A       41     4100
        1        B        B     4142     4241
        2        C        C     4243     4342
        3        D        D     4344     4443
        4       NP       NP     440a      a44
.fi
Dump for each byte of the input data types
.BR "c" " and " "x" "."
.BR "" "Use format " "c" " with data type " "c" " and format " "x" " with data type " "s" "."
Also show the data for both directions, forward and reversed.

.TP
.B "% echo ABCD | datasniffer -d c -n d"
.nf
 P0AbsDec  c(+,%c)  c(+,%x) 
        0        A       41
        1        B       42
        2        C       43
        3        D       44
        4       NP        a
.fi

Emit a single header line followed by one data line each for
the four ascii characters ABCD and the trailing newline.  Each
such line shows the absolute position of that byte (numbered from zero),
the character it corresponds to, and the hexadecimal value of the byte


.TP
.B "% echo ABCDEFGHIJKLMNOPQRSTUVWXYZ \e"
.B "| datasniffer -d s  -fs x -c 5 -n d"
.nf
 P0RelDec  s(+,%x)  s(+,%x)  s(+,%x)  s(+,%x)  s(+,%x) 
        0       41     4142     4243     4344     4445
        5     4546     4647     4748     4849     494a
       10     4a4b     4b4c     4c4d     4d4e     4e4f
       15     4f50     5051     5152     5253     5354
       20     5455     5556     5657     5758     5859
       25     595a     5a0a
.fi
Emit multiple columns of data on each line.


.SH SEE ALSO

.BR "od" "(1), " "mdump" "(1)"

.SH LICENSE

GNU General Public License 2

.SH COPYRIGHT

Copyright (C) 2008 David Mathog and Caltech.

.SH AUTHORS


David Mathog, Biology Division, Caltech <mathog@caltech.edu>

