.TH "execinput" "1" "1.0.1 OCT 23 2006" "drm_tools" "User Commands"

.SH NAME

execinput \- read commands and execute them one line at a time

.SH SYNOPSIS

.BI execinput " [options...]"

.SH DESCRIPTION

.B execinput
reads a series of commands from stdin or a text file and
executes each line as a command.  
.B execinput
may be obtained as part of the 
.B drm_tools
package from:
.B http://sourceforge.net/projects/drmtools/


.SH OPTIONS

.TP
.BI -c " <string>"
Any line which begins with a character contained in 
.B <string>
is a comment
and is not executed.  (Default is to execute all input lines with 1 or more characters.)

.TP
.B -h -help --help -? --??
Print the help message. (Default - do not print help message.)


.TP
.B -ef
Exit on first failure. ( Default - continue processing after a command failure).


.TP
.B -i
Emit version, copyright, license and contact information.( Default - do not emit information.)



.TP
.BI  -in " <input_file>"
Read input from the specified file.  (Default is to read from stdin.)


.TP
.B -loge
Log processing to stderr.  The output format is:
.br
.B STATUS:XXXXXXXX: command
.br
where:
.B STATUS
is either
.B success
or
.B failure;
.B XXXXXXXX
is the hexadecimal exit value returned by the subprocess;
and 
.B command
is the text line which was executed.  (Default is no logging.)


.TP
.BI -logf " <log_file>" 
Log processing to the specified file.
(Default is not to log processing.)

.TP
.BI -wl " <widest_line>"
Widest input line in characters.  (Default 
.B <widest_line>
is 16000.)


.SH EXAMPLES


.TP
.B % execinput -h
List the the command line options.

.TP
.B % echo 'rm foobar' | execinput
Run the command
.B rm foobar


.TP
.B % execinput -in cmdfile -ef -c '#!' -logf processed.log
Read commands from 
.B cmdfile
, treat lines beginning with # or !
as a comment, abort if any command fails, and log status messages to
.B processed.log.

.PD 0
.PP
.B % find . | \\\\ 
.br
.B "  extract -if '/' -ifonly -dl '/' -mt -cols 'mv [1,] [1,-2][cu:-1,]'" |\\\\ 
.PD 0
.TP
.B "  execinput"
Change the names of all files in
or below this directory to upper case.

   



.SH SEE ALSO

.B extract(1)

.SH LICENSE

GNU General Public License 2

.SH COPYRIGHT

Copyright (C) 2002, 2006 David Mathog and Caltech.

.SH AUTHORS

David Mathog, Biology Division, Caltech <mathog@caltech.edu>



