.TH "tarsieve" "1" "1.0.0 JUN 24 2013" "drm_tools" "User Commands"

.SH NAME

tarsieve \- filter, then list or split, a tar file or tar data stream

.SH SYNOPSIS

.BI tarsieve " [options...]"

.SH DESCRIPTION

.B tarsieve
selects a set of records from a tar file or tar data stream and then either
lists them or emits them to one or more tar files, or as a single tar data stream
to stdout.
.B tarsieve
is primarily designed for working with collections of data files which have
been  stored in a tar archive, and where only some of the archive's records are
needed for a partiular task.  This subset may be selected
by name, modification time, size, and so forth.  There are options to eliminate
path  information from names and to eliminate the data payload from files.
.B tarsieve
does not itself create files from a tar file or tar data stream, 
.B tar
must be employed for that purpose.

.B tarsieve
may be obtained as part of the 
.B drm_tools
package from:
.B http://sourceforge.net/projects/drmtools/

On many operating systems
.B tarsieve
must be compiled with large file support if it is to read or write files above a
few gigabytes in size.  If compiled with the
.B gcc
compiler add the command line switches
.B -D_LARGE_FILE_SOURCE -D_FILE_OFFSET_BITS=64 
to include large file support.  The
.B -i
option will show whether or not large files are supported.

When
.B tarsieve
is used to split a tar file or tar data stream the default output file name
template is 
.B frag%.3d.tar. 
The value of the environmental symbol 
.B TARSIEVETEMPLATE 
overrides this default.  

GNU long name records are processed differently than the others.  These
are always read and stored.  They are emitted before the following record
only when the following record has been selected.

Tar files end with two or more null blocks.  These are always ignored on
input and new ones are written at the end of output tar files or tar data
streams.  This allows
.B tarsieve
to accept concatenated tar files as input.  (See the 
.B EXAMPLES
)

.SH FILTERING OPTIONS
All tests are optional, and if present, are applied in the order
shown below.  Records that fail any test are dropped, others are retained.

.TP
.BI -fnge,-fnle " <RECNUM>"
Record number [>= , <=] RECNUM.  
Records are numbered 1 to N.

.TP
.BI -fdge,-fdle " <DATE>"
Records with date [>= , <=] DATE (YYYY-MM-DD hh:mm:ss).

.TP
.BI -fsge,-fsle " <SIZE>"
Records with size [>= , <=] SIZE (decimal size in bytes).

.TP
.BI -fgeq " <GID>"
Records with gid == GID (octal value).

.TP
.BI -fueq " <UID>"
Records with uid == UID (octal value).

.TP
.BI -fgrp " <GROUP>"
Records with gname == GROUP (a string like
.B users
).

.TP
.BI -fown " <OWNER>"
Records with uname == OWNER (a string like
.B John
).

.TP
.BI -frec " <TYPE>"
Records with record type == TYPE.
TYPE is a comma dilimited list of tar record types:
.br
.B all
All of the following
.br
.B reg
Regular file
.br
.B lnk
Hard link
.br
.B sym
Symbolic link
.br
.B chr
Character special
.br
.B blk
Block special
.br
.B dir
Directory
.br
.B fifo
Named pipe
.br
.B cont
Contiguous file
.br
.B other
all other types

.TP
.BI -ffre  " <REGEXP>"
Records whose file name matches the PCRE regular expression.

.TP
.BI -fdre  " <REGEXP>"
Records whose directory name matches the PCRE regular expression.
The tar record
.B name
field actually holds both the file name and the directory name.  
Two filters are provided so that each part of the name may
be targeted separately



.SH SPLITTING OPTIONS
.TP
.BI -n  " <STREAMS>"
Set the number of tar streams to produce, STREAMS must be >0.
(Default = 1).

.TP
.BI -p  " <PHASE>"
PHASE = 0 or default, emit STREAMS streams to STREAMS files.
.br
1 <= PHASE <= STREAMS, only emit contents of the stream specified by PHASE to stdout.

.TP
.BI -c  " <COUNT>"
Emit COUNT tar records for each PHASE to each stream (Default=1).



.SH LISTING OPTIONS
.TP
.B -l
Emit listing information to stderr.

.TP
.B -lx
Like
.B -l,
but also block all other output.

.TP
.BI -lf  " <FIELDS>"
FIELDS is a comma delimited list of fields to
show in a
.B -l
or 
.B -lx
listing.  Fields are:
.br
.B all
all fields
.br
.B nam
file name
.br
.B mod
file protection mask
.br
.B uid
user id
.br
.B gid
group id
.br
.B siz
file size
.br
.B mtm
mtime
.br
.B csm
chksum
.br
.B typ
record type
.br
.B lnm
linkname
.br
.B unm
uname
.br
.B gnm
gname
.br
.B dmj
devmajor
.br
.B dmn
devminor
.br
.B pre
prefix

The default FIELDS value is:
.B siz,typ,nam

.SH OTHER OPTIONS

.TP
.BI  -in " <FILE>"
Read input from FILE.  (Default or -, input is from stdin.)

.TP
.BI  -z
Zero record size.  Selected files are emitted but their contents are dropped.
(Default, retain file contents.)

.TP
.BI  -np
No Path.  Remove the path from the record name.  If nothing remains, drop
the record.  (Default, retain paths in file names.)

.TP
.B -h -help --help -? --??
Print the help message. (Default - do not print help message.)

.TP
.B -i
Emit version, copyright, license and contact information.( Default - do not emit information.)


.SH EXAMPLES

.TP
.B % tarsieve -h
List the the command line options.

.TP
.B % tarsieve -in a.tar -n 4 -p 0 -c 5
(
.B a.tar
holds 20 tar records.) 
Split the input into four output files.  
Records 1-5 go to frag001.tar,
6-10 to frag002.tar, 
11-15 to frag003.tar, and 16-20 to frag004.tar.

.TP
.B % tarsieve -in a.tar -n 4 -p 2 -c 3
(
.B a.tar
holds 20 tar records.) 
Write records 4-6 and 16-17 to stdout.

.TP
.B % cat a.tar b.tar c.tar | tarsieve -lx -lf typ,nam
List the concatenated contents of the three tar files, showing
only the record type and name fields.

.TP
.B % tarsieve -in a.tar -fuid 0 -fgid 1 -frec reg -np >b.tar
Select from
.B a.tar
only those records with 
.B uid
0,
.B gid
1,
and containing a regular file. Remove the path part of the name field
from these records and store the results in
.B b.tar.


.SH SEE ALSO

tar(1),
PCRE(3)

.SH LICENSE

GNU General Public License 2

.SH COPYRIGHT

Copyright (C) 2013 David Mathog and Caltech.

.SH AUTHORS

David Mathog, Biology Division, Caltech <mathog@caltech.edu>



